# Full list of configuration options available at: https://revealjs.com/config/
highlightjs: atom-one-light
reveal:
  width: 1280
  height: 720
  backgroundTransition: "none"
  center: true
  controls: true
  fragmentInURL: true
  fragments: true
  hash: true
  help: true
  hideCursorTime: 2000
  hideInactiveCursor: true
  history: false
  keyboard: true
  overview: true
  progress: true
  touch: true
  vertical-slides: true
  transition: "none"
  zoom: true
  menu:
    side: "left"
    width: "wide"
    numbers: false
    titleSelector: "h1"
    useTextContentForMissingTitles: false
    hideMissingTitles: false
    markers: true
    custom: false
    themes: false
    transitions: false
    openButton: true
    openSlideNumber: true
    keyboard: true
    sticky: false
    autoOpen: true
    delayInit: false
    openOnInit: false
    loadIcons: false
  math:
    macros:
      R: '{{\mathrm{{I}\kern-.15em{R}}}}'
      laplace: '{\Delta}'
      grad: '{\nabla}'
      T: '^{\mathsf{T}}'
      abs: ['\left\lvert #1 \right\rvert', 1]
      det: ['\left\lvert #1 \right\rvert', 1]
      norm: ['\left\Vert #1 \right\Vert', 1]
      iprod: ['\left\langle #1 \right\rangle', 1]
      vec: ['{\mathbf{\boldsymbol{#1}}}', 1]
      mat: ['{\mathbf{\boldsymbol{#1}}}', 1]
      set: ['\mathcal{#1}', 1]
      func: ['\mathrm{#1}', 1]
      trans: ['{#1}\mkern-1mu^{\mathsf{T}}', 1]
      matrix: ['\begin{bmatrix} #1 \end{bmatrix}', 1]
      vector: ['\begin{pmatrix} #1 \end{pmatrix}', 1]
      of: ['\left( #1 \right\)', 1]
      diff: ['\frac{\mathrm{d}{#1}}{\mathrm{d}{#2}}', 2]
      pdiff: ['\frac{\partial {#1}}{\partial {#2}}', 2]
      vc: ['{\mathbf{\boldsymbol{#1}}}', 1]
      qt: ['\hat{\vc {#1}}', 1]
      mt: ['{\mathbf{\boldsymbol{#1}}}', 1]
      pt: ['\boldsymbol{#1}', 1]
      textcolor: ['\color{#1}', 1]
  chart:
    defaults:
      global:
        tooltips: { mode: "point", intersect: true }
        legend: { position: "bottom" }
        plugins: { colorschemes: { scheme: "tableau.Classic10" } }
    bar: { borderWidth: "1" }
    line: { borderWidth: "2", tension: "0" }
    radar: { borderWidth: "2" }
