image: docker:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  only:
    - schedules
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

stackbuild:
  tags: 
    - stack
  stage: build
  only:
    - master
  script:
    - stack setup
    - stack build -j 8 --fast
