stages:
#   - build
  - test
  - deploy

dockerbuild:
  image: docker:latest
  stage: deploy
  only:
    - schedules
  tags:
    - decker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# stackbuild:
#   tags: 
#     - stack
#   stage: build
#   only:
#     - master
#   script:
#     - stack setup
#     - make build
#   artifacts:
#     paths:
#     - dist/decker.zip
#     expire_in: 20 minutes

stacktest:
  stage: test
  tags:
    - docker
  image:
    name: gitlab2.informatik.uni-wuerzburg.de:4567/decker/decker/testcontainer:latest
    entrypoint: [""]
  script:
    - make test

# stacktest:
#   tags: 
#     - stack
#   stage: test
#   only:
#     - master
#   script:
#     - make test
