image: docker:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  only:
    - schedules
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# Well, it seems wie need a different runner for that
# stackdockerbuild:
#   stage: build
#   only:
#     - master
#   script:
#     - stack --docker build
