stages:
  - templates
  - test
  - deploy

templates:
  image: kkarczmarczyk/node-yarn
  stage: templates
  tags:
    - docker
  script:
    - cd resource/support && yarn install
  artifacts:
    paths:
      - resource/support/node_modules

dockerbuild:
  image: docker:latest
  stage: deploy
  only:
    - schedules
  tags:
    - decker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


macbuild:
  tags:
    - mac
  stage: deploy
  only:
    - master
  script:
    - make
    - cp $(stack path | grep "local-install-root" | awk '{printf "%s/bin/decker",$2}') decker
  artifacts:
    paths:
      - decker
      
winbuild:
  stage: deploy
  tags:
    - win
  only:
    - master
  script:
    - "(dir 2>&1 *`|echo CMD);&<# rem #>echo PowerShell"
    - '& stack build'
    - '$binpath=(Join-Path ($(stack path | Select-String -Pattern "local-install-root") -split " ")[1] "bin\decker.exe")'
    - 'Copy-Item $binpath .'
  artifacts:
    paths:
      - decker.exe
# stackbuild:
#   tags: 
#     - stack
#   stage: build
#   only:
#     - master
#   script:
#     - stack setup
#     - make build
#   artifacts:
#     paths:
#     - dist/decker.zip
#     expire_in: 20 minutes

stacktest:
  stage: test
  tags:
    - docker
  image:
    name: gitlab2.informatik.uni-wuerzburg.de:4567/decker/decker/testcontainer:latest
    entrypoint: [""]
  script:
    - make test

# stacktest:
#   tags: 
#     - stack
#   stage: test
#   only:
#     - master
#   script:
#     - make test
