flags: 
  pandoc-citeproc:
    embed_data_files: true
packages:
- '.'
extra-deps:
- haddock-library-1.7.0
- hslua-1.0.1
- hslua-module-text-0.2.0
- HsYAML-0.1.1.2
- libyaml-0.1.0.0
- pandoc-2.4
- pandoc-lens-0.6.3
- pandoc-include-code-1.3.0.0
- skylighting-0.7.4
- skylighting-core-0.7.4
- yaml-0.11.0.0
resolver: lts-12.20
