flags:
  pandoc:
    trypandoc: false
    embed_data_files: false
packages:
  - "."
extra-deps:
- pandoc-2.11.4
- pandoc-types-1.22
- rfc5051-0.2
- haddock-library-1.9.0
- skylighting-0.10.2
- skylighting-core-0.10.2
- jira-wiki-markup-1.3.2
- HsYAML-aeson-0.2.0.0
- commonmark-0.1.1.3
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- doctemplates-0.9
- texmath-0.12.1
- citeproc-0.3.0.5
- lens-4.19.2
- shake-0.19.1
- hslua-1.3.0
resolver: lts-17.0
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
