flags:
  regex-posix:
    _regex-posix-clib: true
  pandoc:
    embed_data_files: false
    trypandoc: false
packages:
  - "."
extra-deps: []

# As of lts-19.13 this is still needed on M1 macOS.
extra-include-dirs:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi

resolver: lts-19.17

# Maybe we still need this on Windows
# ghc-options:
#   "$locals": -fhide-source-paths -Wno-missing-home-modules
#   "$everything": -haddock

