flags:
  regex-posix:
    _regex-posix-clib: true
  pandoc:
    embed_data_files: false
    trypandoc: false
packages:
  - "."
extra-deps: []

resolver: lts-19.6
# ghc-options:
#   "$locals": -fhide-source-paths -Wno-missing-home-modules
#   "$everything": -haddock
