flags:
  pandoc-citeproc:
    embed_data_files: true
  regex-posix:
      _regex-posix-clib: true
packages:
  - "."
extra-deps:
   - regex-posix-clib-2.7
   - lens-4.19.2
   - shake-0.19.4
resolver: lts-15.10
compiler: ghc-8.10.3
