# Default meta data

poll-server: wss://tramberend.bht-berlin.de/quizzer/quiz
# poll-server: ws://localhost:3003/quiz

# Use CSS augmentation without changes to the default template
template:
  css:
    - support/css/mono.css
  js:
    - support/js/mono.js

palette:
  colors:
    light: # Solarized Light
      - "#fdf6e3"
      - "#eee8d5"
      - "#93a1a1"
      - "#839496"
      - "#657b83"
      - "#586e75"
      - "#073642"
      - "#002b36"
      - "#dc322f"
      - "#cb4b16"
      - "#b58900"
      - "#859900"
      - "#2aa198"
      - "#268bd2"
      - "#6c71c4"
      - "#d33682"
    dark: # Solarized Dark
      - "#002b36"
      - "#073642"
      - "#586e75"
      - "#657b83"
      - "#839496"
      - "#93a1a1"
      - "#eee8d5"
      - "#fdf6e3"
      - "#dc322f"
      - "#cb4b16"
      - "#b58900"
      - "#859900"
      - "#2aa198"
      - "#268bd2"
      - "#6c71c4"
      - "#d33682"
  contrast: 0.3

reveal:
  reveal:
  backgroundTransition: "slide"
  center: true
  controls: true
  fragmentInURL: true
  fragments: true
  hash: true
  height: 1080
  help: true
  hideCursorTime: 2000
  hideInactiveCursor: true
  history: false
  keyboard: true
  margin: 0.05
  overview: true
  progress: true
  slideNumber: true
  touch: true
  transition: "slide"
  vertical-slides: true
  viewDistance: 2
  width: 1920

css-variables:
  block-border-radius: 0.2em;
