reveal:
  backgroundTransition: "none"
  center: false
  controls: true
  fragmentInURL: true
  fragments: true
  hash: true
  help: true
  hideCursorTime: 2000
  hideInactiveCursor: true
  history: false
  keyboard: true
  overview: false
  pdfMaxPagesPerSlide: 10
  pdfSeparateFragments: false
  progress: false
  slideNumber: true
  touch: true
  vertical-slides: true
  transition: "none"
  width: 1280
  height: 720
  viewDistance: 2

chart:
  defaults:
    font: {family: "Lato", size: 20 }
    plugins:
      colorschemes:
        scheme: "tableau.Classic10"
      title:
        font: { weight: "normal", size: 30 }
      legend:
        position: "bottom"

math:
  macros:
    R: '{{\\mathrm{{I}\\kern-.15em{R}}}}'
    laplace: '{\\Delta}'
    grad: '{\\nabla}'
    T: '^{\\mathsf{T}}'
    abs: ['\\left\\lvert #1 \\right\\rvert', 1]
    det: ['\\left\\lvert #1 \\right\\rvert', 1]
    norm: ['\\left\\Vert #1 \\right\\Vert', 1]
    iprod: ['\\left\\langle #1 \\right\\rangle', 1]
    vec: ['{\\mathbf{\\boldsymbol{#1}}}', 1]
    mat: ['{\\mathbf{\\boldsymbol{#1}}}', 1]
    set: ['\\mathcal{#1}', 1]
    func: ['\\mathrm{#1}', 1]
    trans: ['{#1}\\mkern-1mu^{\\mathsf{T}}', 1]
    matrix: ['\\begin{bmatrix} #1 \\end{bmatrix}', 1]
    vector: ['\\begin{pmatrix} #1 \\end{pmatrix}', 1]
    of: ['\\left( #1 \\right\\)', 1]
    diff: ['\\frac{\\mathrm{d}{#1}}{\\mathrm{d}{#2}}', 2]
    pdiff: ['\\frac{\\partial {#1}}{\\partial {#2}}', 2]
    vc: ['{\\mathbf{\\boldsymbol{#1}}}', 1]
    qt: ['\\hat{\\vc {#1}}', 1]
    mt: ['{\\mathbf{\\boldsymbol{#1}}}', 1]
    pt: ['\\boldsymbol{#1}', 1]
    textcolor: ['\\color{#1}', 1]

# other settings
highlightjs: xcode

# Language dictionary. Currently for quiz elements
dictionary:
  de:
    exam:
      Easy: Leicht
      Hard: Schwer
      Medium: Mittelschwer
      again-button: Nochmal
      placeholder: Antwort eingeben
      points: Punkte
      solution: Lösung
      solve-button: Lösen
      reset-button: Zurücksetzen
    quiz:
      solution: Lösung
      reset-button: Zurücksetzen
      input-placeholder: Eingeben und 'Enter'
      qmi-drag-hint: Objekte per Drag&Drop ziehen...
      qmi-drop-hint: ...und hier in die richtige Kategorie einsortieren.
      solve-button: Lösung
  en:
    exam:
      Easy: Easy
      Hard: Hard
      Medium: Medium
      again-button: Again
      placeholder: Type in answer
      points: Points
      solution: Solution
      solve-button: Solve
      reset-button: Reset
    quiz:
      solution: Show Solution
      reset-button: Reset
      input-placeholder: Type and press 'Enter'
      qmi-drag-hint: Drag items from here...
      qmi-drop-hint: ...and put them here into the correct category.
      solution-button: Show Solution

palette:
  colors:
    light:
      - "#ffffff"
      - "#dbdbdb"
      - "#b7b7b7"
      - "#939393"
      - "#6f6f6f"
      - "#4a4a4a"
      - "#252525"
      - "#000000"
      - "#ff0000"
      - "#ffa500"
      - "#ffff00"
      - "#83B818"
      - "#00ffa5"
      - "#2a9ddf"
      - "#a500ff"
      - "#ff00ff"
    dark:
      - "#000000"
      - "#252525"
      - "#4a4a4a"
      - "#6f6f6f"
      - "#939393"
      - "#b7b7b7"
      - "#dbdbdb"
      - "#ffffff"
      - "#ff0000"
      - "#ffa500"
      - "#ffff00"
      - "#83B818"
      - "#00ffa5"
      - "#2a9ddf"
      - "#a500ff"
      - "#ff00ff"