# Sane defaults for reval.js
backgroundTransition: "none"
center: true
controls: true
fragmentInURL: true
fragments: true
hash: true
help: true
hideCursorTime: 2000
hideInactiveCursor: true
history: false
keyboard: true
menu: true
overview: true
progress: true
test123: "test123"
title: "|title|"
touch: true
transition: "none"
zoom: true

# These are some sane defaults we need
align-global: left
border-decoration-padding: 10px
border-decoration-style: solid
border-decoration-width: 20px
font-size-base: 28px
margin-columns: 0em
margin: 0.05
spacing-vertical-base: 0.5em

# default settings for whiteboard buttons
whiteboard-active-color: rgb(42,157,223)
whiteboard-background-color: rgb(250,250,250)
whiteboard-icon-size: 2vmin
whiteboard-inactive-color: lightgrey

# Language dictionary. Currently for quiz elements
dictionary:
  de:
    exam:
      Easy: Leicht
      Hard: Schwer
      Medium: Mittelschwer
      again-button: Nochmal
      placeholder: Antwort eingeben
      points: Punkte
      solution: Lösung
      solve-button: Lösen
    quiz:
      input-placeholder: Eingeben und 'Enter'
      qmi-drag-hint: Objekte per Drag&Drop ziehen...
      qmi-drop-hint: ...und hier in die richtige Kategorie einsortieren.
      solve-button: Lösung
  en:
    exam:
      Easy: Easy
      Hard: Hard
      Medium: Medium
      again-button: Again
      placeholder: Type in answer
      points: Points
      solution: Solution
      solve-button: Solve
    quiz:
      input-placeholder: Type and press 'Enter'
      qmi-drag-hint: Drag items from here...
      qmi-drop-hint: ...and put them here into the correct category.
      solution-button: Show Solution
