on:
  push:
    branches:
      - "develop"

name: Test Develop
jobs:
  build-all-platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Decker latest (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.4.2"
          enable-stack: true
          stack-no-global: true
          stack-version: "latest"
          stack-setup-ghc: true

      - name: Build & test
        run: |
          stack test
          stack --local-bin-path=dist install

      - name: Rename executable
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          mv dist/decker "dist/decker-latest-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}"

      - name: Rename executable
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mv dist/decker.exe "dist/decker-latest-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}.exe"

      - name: Delete last release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: 'latest'

      - name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          name: 'latest'
          tag_name: latest
          draft: true
          files: | 
            readme.md
            changelog.md
            dist/**
