on:
  push:
    branches:
      - master
    tags:
      - "*"

name: Build Release
jobs:
  build-all-platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Decker Release (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true
          stack-no-global: true
          stack-version: "latest"
          stack-setup-ghc: true

      - name: Build & test
        run: |
          stack test
          stack --local-bin-path=dist install

      - name: Rename executable
        if: matrix.config.os != 'windows-latest'
        run: |
          mv dist/decker "dist/decker-${{ github.sha }}-${{ runner.os }}-${{ runner.arch }}"

      - name: Rename executable
        if: matrix.config.os == 'windows-latest'
        run: |
          mv dist/decker.exe "dist/decker-${{ github.sha }}-${{ runner.os }}-${{ runner.arch }}.exe"

      - name: Release
        uses: "softprops/action-gh-release@v1"
        if: startsWith(github.ref, 'refs/tags/')
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false
        with:
          files: "dist/*"
