on:
  push:
    branches:
      - master

name: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Decker Release (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true
          stack-no-global: true
          stack-version: "latest"
          stack-setup-ghc: true

      - name: Build & test Decker 
        run: |
          stack test
          stack --local-bin-path=dist install
          mv dist/decker "dist/decker-${{ github.sha }}-${{ runner.os }}-${{ runner.arch }}"
      
      - name: Release 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ matrix.os }}"
          prerelease: true
          title: "Development Build (${{ matrix.os }})"
          files: "dist/decker-${{ github.sha }}-${{ runner.os }}-${{ runner.arch }}"